services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: file_cloud_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d file_cloud_db" ]
      interval: 5s
      timeout: 5s
      retries: 7
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql:ro

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWKS_URI: ${JWKS_URI}

    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

volumes:
  postgres_data:
